version: "3"

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  ideasoft-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ideasoft
      MYSQL_ROOT_PASSWORD: 123456
    container_name: ideasoft-db   
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  ideasoftassesment:
    container_name: ideasoftassesment
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8090:8080"
    depends_on:
      - ideasoft-db
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
